#!/usr/bin/env python3
"""
Rebuild specific glyphs across all weights.

This script rebuilds only the specified glyphs (by figure number) for all six weights,
without regenerating the entire font.
"""

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

# Configuration
SCRIPT_DIR = Path(__file__).parent
PROJECT_DIR = SCRIPT_DIR.parent
SRC_DIR = PROJECT_DIR / "calyptapis" / "src"
OUTPUT_DIR = PROJECT_DIR / "calyptapis" / "maj"

# Weight configurations: weight name -> pen_height multiplier
WEIGHTS = {
    "UltraLight": 0.06,
    "Light": 0.09,
    "Normal": 0.12,
    "SemiBold": 0.15,
    "Bold": 0.18,
    "Black": 0.21,
}

# Glyph figure numbers to rebuild (from beginfig(N))
# 414 = U+10414 𐐔 (Dee)
# 4008 = U+1041C 𐐜 (Thee)
GLYPHS_TO_REBUILD = [414, 4008]

# Mapping of figure numbers to source files (absolute paths)
GLYPH_SOURCES = {
    414: SRC_DIR / "letters" / "U10414.mp",
    4008: SRC_DIR / "letters" / "U1041c.mp",
}


def create_temp_mp_file(pen_height_mult: float, glyphs: list[int], temp_dir: Path) -> Path:
    """Create a temporary .mp file that only includes the specified glyphs."""

    mp_content = f"""% Temporary file for rebuilding specific glyphs
% Auto-generated by rebuild_glyphs.py

% Base font parameters
numeric font_size, pen_height, x_height;
font_size  := 72pt;
pen_height := {pen_height_mult} * font_size;

numeric x_radius, y_radius, Ox, Oy;
x_radius := 0.45 * font_size;
y_radius := 0.5 * font_size;
x_height := x_radius;
Ox := 0;
Oy := 0;

% Pens
pen peg_pen ;    peg_pen    = pensquare scaled pen_height;
pen thin_pen ;   thin_pen   = pencircle scaled pen_height;
pen flat_pen ;   flat_pen   = makepen ((0,0)--(pen_height,0));
pen tall_pen ;   tall_pen   = makepen ((0,0)--(0,pen_height));
pen loz_pen ;    loz_pen    = makepen (fullcircle xscaled (0.25 * pen_height) yscaled pen_height);

% Format parameters
outputtemplate := "%j-%c.svg";
outputformat := "svg";

% Include only the glyphs we need to rebuild
"""

    for glyph_num in glyphs:
        if glyph_num in GLYPH_SOURCES:
            # Use absolute path for the input file
            mp_content += f"input {GLYPH_SOURCES[glyph_num].as_posix()};\n"

    mp_content += "\nend\n"

    mp_file = temp_dir / "rebuild.mp"
    mp_file.write_text(mp_content)
    return mp_file


def rebuild_glyphs(glyphs: list[int] = None, weights: list[str] = None):
    """Rebuild specified glyphs for specified weights."""

    if glyphs is None:
        glyphs = GLYPHS_TO_REBUILD

    if weights is None:
        weights = list(WEIGHTS.keys())

    print(f"Rebuilding glyphs: {glyphs}")
    print(f"For weights: {weights}")
    print()

    for weight_name in weights:
        if weight_name not in WEIGHTS:
            print(f"Unknown weight: {weight_name}, skipping")
            continue

        pen_mult = WEIGHTS[weight_name]
        print(f"Building {weight_name} (pen_height = {pen_mult} * font_size)...")

        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)

            # Create the temporary .mp file
            mp_file = create_temp_mp_file(pen_mult, glyphs, temp_path)

            # Run mpost
            result = subprocess.run(
                ["mpost", mp_file.name],
                cwd=temp_path,
                capture_output=True,
                text=True
            )

            if result.returncode != 0:
                print(f"  ERROR: mpost failed for {weight_name}")
                print(f"  stdout: {result.stdout}")
                print(f"  stderr: {result.stderr}")
                continue

            # Copy the generated SVGs to the output directory
            weight_dir = OUTPUT_DIR / weight_name
            weight_dir.mkdir(parents=True, exist_ok=True)

            for glyph_num in glyphs:
                svg_name = f"rebuild-{glyph_num}.svg"
                src_svg = temp_path / svg_name

                if src_svg.exists():
                    # Rename to match expected naming convention
                    dest_name = f"calyptapis-{glyph_num}.svg"
                    dest_svg = weight_dir / dest_name
                    shutil.copy(src_svg, dest_svg)
                    print(f"  Created: {dest_svg.relative_to(PROJECT_DIR)}")
                else:
                    print(f"  WARNING: {svg_name} not found in build output")

    print()
    print("Done!")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Rebuild specific glyphs across weights")
    parser.add_argument(
        "--glyphs", "-g",
        type=int,
        nargs="+",
        default=GLYPHS_TO_REBUILD,
        help=f"Figure numbers to rebuild (default: {GLYPHS_TO_REBUILD})"
    )
    parser.add_argument(
        "--weights", "-w",
        nargs="+",
        default=list(WEIGHTS.keys()),
        help=f"Weights to rebuild (default: all)"
    )

    args = parser.parse_args()
    rebuild_glyphs(args.glyphs, args.weights)
